_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.7
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
